### ISSUE TITLE
Consistency with `racc` module namespacing

### ISSUE THREAD

**Issue by christhekeele** [sparklemotion/rexical#19]
In `racc`, a parser namespace like `class Search::Parser` gets expanded to:

```ruby
module Search
  class Parser < Racc::Parser
    #...
  end
end
```

In `rexical`, a parser namespace like `class Search::Parser` gets expanded to:

```ruby
class Search::Parser < Racc::Parser
  #...
end
```

This goes against ruby best practices and makes it impossible to do something like:

```ruby
require "search/parser"
module Search
  # Reference parser
end
```

This fails because the runtime doesn't have a proper `Search` module defined yet when loading the `rexical` part of the parser, which is why best practice is to always nest module namespaces when adding to them as `racc` does. You can work around it in a few ways:

1. Dummy namespace:

    ```ruby
    module Search; end
    require "search/parser"
    module Search
      # Reference parser
    end
    ```

2. Terminal require:

    ```ruby
    module Search
      # Reference parser
    end
    require "search/parser"
    ```

The first is ungainly; the second hides the requirement and also means you can't reference the parser outside a method (i.e. some class method or constant that helps generate general search functionality).

Switching to the `racc` style of module generation would make this more intuitive.

**Comment by flavorjones** [comment]
If you'd like to submit a pull request that adds a CLI flag to _nest_ the class rather than use the compact style (I'm using the terminology from [Rubocop's style cop](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/ClassAndModuleChildren), I'd be open to reviewing and merging it!

I've always worked around this by nesting the class in the header of my file. An example of this usage in the wild is where [Nokogiri tokenizes CSS queries](https://github.com/sparklemotion/nokogiri/blob/main/lib/nokogiri/css/tokenizer.rex#L1-L4):

```
module Nokogiri
module CSS
class Tokenizer

macro
  nl        \n|\r\n|\r|\f
  w         [\s]*
  nonascii  [^\0-\177]
...
```
